CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(40),
BIRTH_DATE DATE,
SEX VARCHAR(10),
SALARY INT,
SUPER_ID INT,
BRANCH_ID INT
);

CREATE TABLE BRANCH(
BRANCH_ID INT PRIMARY KEY,
BRANCH_NAME VARCHAR(50),
MGR_ID INT,
MGR_START_DATE DATE,
FOREIGN KEY(MGR_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE SET NULL
);

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY(BRANCH_ID)
REFERENCES BRANCH(BRANCH_ID)
ON DELETE SET NULL;

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY(SUPER_ID)
REFERENCES EMPLOYEE(EMP_ID)
ON DELETE SET NULL;

CREATE TABLE CLIENT(
CLIENT_ID INT PRIMARY KEY,
CLIENT_NAME VARCHAR(40),
BRANCH_ID INT,
FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE SET NULL
);

CREATE TABLE WORKS_WITH(
EMP_ID INT ,
CLIENT_ID INT ,
TOTAL_SALES INT,
PRIMARY KEY(EMP_ID, CLIENT_ID),
FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE CASCADE,
FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE
);

CREATE TABLE BRANCH_SUPPLIER(
BRANCH_ID INT,
BRANCH_NAME VARCHAR(50),
SUPPLY_TYPE VARCHAR(50),
PRIMARY KEY(BRANCH_ID, BRANCH_NAME),
FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE
);
