---------------------AFTER INSERT Trigger (Logging))----------------------

--CREATE FUNCTION
CREATE OR REPLACE FUNCTION AFTER_INSERT_FN()
RETURNS TRIGGER AS $$
BEGIN
	INSERT INTO AUDIT_LOG(EMP_ID, ACTION, NEW_SALARY)
	VALUES(NEW.EMP_ID, 'INSERT', NEW.SALARY);
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

--CREATE TRIGGER
CREATE TRIGGER AFTER_INSERT_TRIGGER
AFTER INSERT
ON EMPLOYEES
FOR EACH ROW
EXECUTE FUNCTION AFTER_INSERT_FN();

--INSERT DATA AND CHECK
INSERT INTO EMPLOYEES(NAME, SALARY) VALUES('MAHESH', 5000);
INSERT INTO EMPLOYEES(NAME, SALARY) VALUES('RIO', 10000);

--CHECK EMPLOYEES TABLE
SELECT * FROM AUDIT_LOG;

--HOW TO DROP
DROP TRIGGER AFTER_INSERT_TRIGGER ON EMPLOYEES;
DROP FUNCTION AFTER_INSERT_FN();