------------------------AFTER DELETE (LOGGONG TRIGGER)-------------------------
--Important:
--This runs ONLY if delete is allowed
--If BEFORE DELETE exists → ❌ this will NOT run

--CREATE FUNCTION
CREATE OR REPLACE FUNCTION AFTER_DELETE_FN()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO AUDIT_LOG(EMP_ID, ACTION, OLD_SALARY)
VALUES(OLD.EMP_ID, 'DELETE', OLD.SALARY);
RETURN OLD;
END;
$$ LANGUAGE PLPGSQL;

--CREATE TRIGGER
CREATE TRIGGER AFTER_DELETE_TRIGGER
AFTER DELETE
ON EMPLOYEES
FOR EACH ROW
EXECUTE FUNCTION AFTER_DELETE_FN();

--DELETE AND CHECK
DELETE FROM EMPLOYEES WHERE EMP_ID = 10;

--CHECK EMPLOYEES TABLE
SELECT * FROM AUDIT_LOG;
SELECT * FROM EMPLOYEES;

--HOW TO DROP
DROP FUNCTION AFTER_DELETE_FN();
DROP TRIGGER AFTER_DELETE_TRIGGER ON EMPLOYEES;