---------------------AFTER UPDATE → Logging Trigger----------------------

--CREATE FUNCTION
CREATE OR REPLACE FUNCTION AFTER_UPDATE_FN()
RETURNS TRIGGER AS $$
BEGIN
IF NEW.SALARY <> OLD.SALARY THEN
INSERT INTO AUDIT_LOG(EMP_ID, ACTION, OLD_SALARY, NEW_SALARY)
VALUES(OLD.EMP_ID, 'UPDATE', OLD.SALARY, NEW.SALARY);
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

--CREATE TRIGGER
CREATE TRIGGER AFTER_UPDATE_TRIGGER
AFTER UPDATE
ON EMPLOYEES
FOR EACH ROW
EXECUTE FUNCTION AFTER_UPDATE_FN();

--UPDATE DATA AND CHECK
UPDATE EMPLOYEES
SET SALARY = 100000
WHERE EMP_ID = 5;

--CHECK EMPLOYEES TABLE
SELECT * FROM AUDIT_LOG;
SELECT * FROM employees;

--HOW TO DROP
DROP TRIGGER AFTER_UPDATE_TRIGGER ON EMPLOYEES;
DROP FUNCTION AFTER_UPDATE_FN();