------------------------BEFORE DELETE (BLOCK DELETE)-------------------------

--CREATE FUNCTION
CREATE OR REPLACE FUNCTION BEFORE_DELETE_FN()
RETURNS TRIGGER AS $$
BEGIN
RAISE EXCEPTION 'DELETE NOT ALLOWED';
RETURN OLD;
END;
$$ LANGUAGE PLPGSQL;

--CREATE TRIGGER
CREATE TRIGGER BEFORE_DELETE_TRIGGER
BEFORE DELETE
ON EMPLOYEES
FOR EACH ROW
EXECUTE FUNCTION BEFORE_DELETE_FN();

--DELETE AND CHECK
DELETE FROM EMPLOYEES;

--CHECK EMPLOYEES TABLE
SELECT * FROM EMPLOYEES;

--Important:
--AFTER DELETE runs ONLY if BEFORE delete is allowed SO
--If BEFORE DELETE exists → THEN AFTER DELETE will NOT run
--HOW TO DROP
DROP FUNCTION BEFORE_DELETE_FN();
DROP TRIGGER BEFORE_DELETE_TRIGGER ON EMPLOYEES;