---------------------BEFORE UPDATE → Validation/Check Trigger----------------------

--CREATE FUNCTION
CREATE OR REPLACE FUNCTION BEFORE_UPDATE_FN()
RETURNS TRIGGER AS $$
BEGIN
IF NEW.SALARY < OLD.SALARY THEN
RAISE NOTICE 'SALARY DECREASED';
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

--CREATE TRIGGER
CREATE TRIGGER BEFORE_UPDATE_TRIGGER
BEFORE UPDATE
ON EMPLOYEES
FOR EACH ROW
EXECUTE FUNCTION BEFORE_UPDATE_FN();

--UPDATE DATA AND CHECK
UPDATE EMPLOYEES
SET SALARY = 9000
WHERE EMP_ID = 5;

--CHECK EMPLOYEES TABLE
SELECT * FROM EMPLOYEES;

--HOW TO DROP
DROP TRIGGER BEFORE_UPDATE_TRIGGER ON EMPLOYEES;
DROP FUNCTION BEFORE_UPDATE_FN();