---------------------BEFORE INSERT TRIGGER(VALIDATION)----------------------

--CREATE FUNCTION
CREATE OR REPLACE FUNCTION BEFORE_INSERT_FN ()
RETURNS TRIGGER AS $$
BEGIN
IF NEW.SALARY < 10000 THEN
RAISE EXCEPTION 'SALARY MUST BE >= 10000';
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

--CREATE TRIGGER
CREATE TRIGGER BEFORE_INSERT_TRIGGER
BEFORE INSERT
ON EMPLOYEES
FOR EACH ROW
EXECUTE FUNCTION BEFORE_INSERT_FN();

--INSERT DATA AND CHECK
INSERT INTO EMPLOYEES(NAME, SALARY) VALUES('MAHESH', 5000);
INSERT INTO EMPLOYEES(NAME, SALARY) VALUES('RIO', 10000);

--CHECK EMPLOYEES TABLE
SELECT * FROM EMPLOYEES;

--HOW TO DROP
DROP TRIGGER BEFORE_INSERT_TRIGGER ON EMPLOYEES;
DROP FUNCTION BEFORE_INSERT_FN();