------------TRIGGERS----------------
CREATE TABLE EMPLOYEES (
	EMP_ID SERIAL PRIMARY KEY,
	NAME TEXT,
	SALARY DECIMAL(10, 2)
);

CREATE TABLE AUDIT_LOG(
	EMP_ID SERIAL,
	ACTION TEXT,
	OLD_SALARY DECIMAL(10, 2),
	NEW_SALARY DECIMAL(10, 2),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);