--TABLE CREATION
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT,
    EMPLOYEE_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    GENDER VARCHAR(10),
    AGE INT,
    SALARY INT,
    EXPERIENCE_YEARS INT,
    CITY VARCHAR(50),
    PERFORMANCE_SCORE INT,
    BONUS INT,
    STATUS VARCHAR(20)
);

--INSERTING DATA
INSERT INTO EMPLOYEES VALUES
(1, 'RAHUL', 'IT', 'MALE', 25, 45000, 2, 'HYDERABAD', 78, 5000, 'ACTIVE'),
(2, 'SNEHA', 'HR', 'FEMALE', 30, 60000, 5, 'BANGALORE', 88, NULL, 'ACTIVE'),
(3, 'ARJUN', 'FINANCE', 'MALE', 35, 75000, 8, 'CHENNAI', 92, 12000, 'INACTIVE'),
(4, 'PRIYA', 'IT', 'FEMALE', 28, 52000, 4, 'HYDERABAD', 81, 7000, 'ACTIVE'),
(5, 'KIRAN', 'SALES', 'MALE', 40, 40000, 10, 'MUMBAI', 65, NULL, 'INACTIVE'),
(6, 'ANJALI', 'HR', 'FEMALE', 26, 48000, 3, 'DELHI', 73, 4000, 'ACTIVE'),
(7, 'VIKRAM', 'FINANCE', 'MALE', 45, 95000, 15, 'PUNE', 96, 20000, 'ACTIVE'),
(8, 'MEENA', 'SALES', 'FEMALE', 32, 55000, 6, 'MUMBAI', 84, 8000, 'INACTIVE'),
(9, 'RAVI', 'IT', 'MALE', 29, 68000, 5, 'HYDERABAD', 90, 10000, 'ACTIVE'),
(10, 'DIVYA', 'MARKETING', 'FEMALE', 27, 47000, 3, 'BANGALORE', 75, NULL, 'ACTIVE');

SELECT * FROM EMPLOYEES;

/* CREATE A SALARY CATEGORY COLUMN:
SALARY >= 70000 → 'HIGH'
SALARY >= 50000 → 'MEDIUM'
ELSE → 'LOW'
USE: EMPLOYEE_NAME, SALARY, SALARY_CATEGORY */
SELECT
	EMPLOYEE_NAME,
	SALARY,
	CASE
	WHEN SALARY >= 70000 THEN 'HIGH'
	WHEN SALARY >= 50000 THEN 'MEDIUM'
	ELSE 'LOW'
	END AS SALARY_CATEGORY
FROM EMPLOYEES;

/* CREATE AN AGE GROUP COLUMN:
AGE < 30 → 'YOUNG'
AGE BETWEEN 30 AND 40 → 'ADULT'
ELSE → 'SENIOR'
SHOW: EMPLOYEE_NAME, AGE, AGE_GROUP */
SELECT
	EMPLOYEE_NAME,
	AGE,
	CASE
	WHEN AGE < 30 THEN 'YOUNG'
	WHEN AGE BETWEEN 30 AND 40 THEN 'ADULT'
	ELSE 'SENIOR'
	END AS AGE_GROUP
FROM EMPLOYEES;

/* COUNT EMPLOYEES IN EACH SALARY_CATEGORY:
SALARY >= 70000 → 'HIGH'
SALARY >= 50000 → 'MEDIUM'
ELSE → 'LOW'
SHOW: SALARY_CATEGORY, TOTAL_EMPLOYEES */
SELECT
	CASE
	WHEN SALARY >= 70000 THEN 'HIGH'
	WHEN SALARY >= 50000 THEN 'MEDIUM'
	ELSE 'LOW'
	END AS SALARY_CATEGORY,

	COUNT(*) AS TOTAL_EMPLOYEES 
FROM EMPLOYEES
GROUP BY CASE
	WHEN SALARY >= 70000 THEN 'HIGH'
	WHEN SALARY >= 50000 THEN 'MEDIUM'
	ELSE 'LOW'
	END;

/* Find TOTAL SALARY by AGE_GROUP:
AGE GROUP RULES:
AGE < 30 → 'YOUNG'
AGE BETWEEN 30 AND 40 → 'ADULT'
ELSE → 'SENIOR'
SHOW: AGE_GROUP, TOTAL_SALARY */
SELECT
	CASE
	WHEN AGE < 30 THEN 'YOUNG'
	WHEN AGE BETWEEN 30 AND 40 THEN 'ADULT'
	ELSE 'SENIOR'
	END AS AGE_GROUP,
	SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY CASE
		 WHEN AGE < 30 THEN 'YOUNG'
		 WHEN AGE BETWEEN 30 AND 40 THEN 'ADULT'
		 ELSE 'SENIOR'
		 END;

/* CREATE A COLUMN CALLED PERFORMANCE_LABEL USING RANK():
RULES:
TOP 2 HIGHEST SALARIES IN EACH DEPARTMENT → 'TOP PERFORMER'
OTHERS → 'NORMAL'
SHOW: EMPLOYEE_NAME, DEPARTMENT, SALARY, PERFORMANCE_LABEL */
WITH CTE AS(
SELECT
	EMPLOYEE_NAME,
	DEPARTMENT,
	SALARY,

	RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES
)
SELECT
	EMPLOYEE_NAME,
	DEPARTMENT,
	SALARY,
	CASE
	WHEN RANK_ <= 2 THEN 'TOP PERFORMER'
	ELSE 'NORMAL'
	END AS PERFORMANCE_LABEL
FROM CTE;

/* CREATE A KPI QUERY THAT RETURNS ALL OF THESE IN ONE QUERY:
TOTAL_EMPLOYEES
ACTIVE_EMPLOYEES
INACTIVE_EMPLOYEES
HIGH_SALARY_EMPLOYEES
(SALARY >= 70000)
AVG_SALARY */
WITH CTE AS(
SELECT
	COUNT(*) AS TOTAL_EMPLOYEES,
	
	SUM(
		CASE
			WHEN STATUS = 'ACTIVE' THEN 1
			ELSE 0
		END
	) AS ACTIVE_EMPLOYEES,
	
	SUM(
		CASE
			WHEN STATUS = 'INACTIVE' THEN 1
			ELSE 0
		END
	) AS INACTIVE_EMPLOYEES,

	SUM(
		CASE
			WHEN SALARY >= 70000 THEN 1
			ELSE 0
		END
	) AS HIGH_SALARY_EMPLOYEES,
	
	AVG(SALARY) AS AVG_SALARY
	
FROM EMPLOYEES
)
SELECT
	TOTAL_EMPLOYEES,
	ACTIVE_EMPLOYEES,
	INACTIVE_EMPLOYEES,
	HIGH_SALARY_EMPLOYEES,
	AVG_SALARY
FROM CTE;




