--TO CREATE TABLE
CREATE TABLE STUDENT (
	STUDENT_ID INT PRIMARY KEY,
	NAME VARCHAR(25),
	MAJOR VARCHAR(30)
);

--SELECT QUERY TO RETRIEVE DATA
SELECT * FROM STUDENT;

--SELECT QUERY TO RETRIEVE SPECIFIC COLUMN DATA
SELECT NAME, MAJOR FROM STUDENT;