--Where clause examoles
SELECT * FROM STUDENT
WHERE COURSE = 'ECE';

--WHERE WITH GREATER THAN
SELECT * FROM STUDENT
WHERE AGE > 20;

--WHERE WITH LESS THAN
SELECT * FROM STUDENT
WHERE MARKS < 80;

--WHERE WITH AND
SELECT * FROM STUDENT
WHERE COURSE = 'ECE' AND MARKS > 90;

--WHERE WITH OR
SELECT * FROM STUDENT
WHERE COURSE = 'ECE' OR COURSE = 'CSE';

--WHERE WITH BETWEEN
SELECT * FROM STUDENT
WHERE MARKS BETWEEN 70 AND 85;

--WHERE WITH IN
SELECT * FROM STUDENT
WHERE COURSE IN('ECE', 'CSE');

--WHERE WITH LIKE (PATTERN SEARCH)
SELECT * FROM STUDENT
WHERE NAME LIKE 'M%';