--Find employees whose salary is greater than their department average
--Use JOIN with a subquery (derived table)
SELECT E.* FROM EMPLOYEES E
JOIN (SELECT DEPT_ID, AVG(SALARY) AS AVG_SAL 
FROM EMPLOYEES
GROUP BY DEPT_ID) D
ON E.DEPT_ID = D.DEPT_ID
WHERE E.SALARY > D.AVG_SAL;

--Find employees who belong to the department having highest average salary
SELECT E.* FROM EMPLOYEES E
INNER JOIN (SELECT DEPT_ID, AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
GROUP BY DEPT_ID) D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.AVG_SAL = (SELECT MAX(AVG_SAL) FROM 
(SELECT AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
GROUP BY DEPT_ID) X
);

--Find employees who belong to the department with lowest average salary
SELECT E.* FROM EMPLOYEES E
INNER JOIN (SELECT DEPT_ID, AVG(SALARY) AS AVG_SAL 
FROM EMPLOYEES
GROUP BY DEPT_ID) D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.AVG_SAL = (SELECT MIN(AVG_SAL) 
FROM(SELECT AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
GROUP BY DEPT_ID) X
);

--Find employees whose salary is equal to department maximum salary using JOIN
SELECT E.* FROM EMPLOYEES E
INNER JOIN (SELECT DEPT_ID, MAX(SALARY) AS MAX_SAL 
FROM EMPLOYEES
GROUP BY DEPT_ID) D
ON E.DEPT_ID = D.DEPT_ID
WHERE E.SALARY = D.MAX_SAL;

--Find employees whose salary is less than department average using JOIN
SELECT E.* FROM EMPLOYEES E
INNER JOIN (SELECT DEPT_ID, AVG(SALARY) AS AVG_SAL
FROM EMPLOYEES
GROUP BY DEPT_ID) D
ON E.DEPT_ID = D.DEPT_ID
WHERE E.SALARY < D.AVG_SAL;



