--TABLE CREATION:
CREATE TABLE DEPARTMENT_SALES (
	ID INT,
	DEPARTMENT VARCHAR(50),
	SALE_DATE DATE,
	SALES INT
);

--INSERTING DATA
INSERT INTO
	DEPARTMENT_SALES
VALUES
	(1, 'Electronics', '2026-01-01', 1000),
	(2, 'Electronics', '2026-01-02', 1200),
	(3, 'Electronics', '2026-01-03', 900),
	(4, 'Electronics', '2026-01-04', 1500),
	(5, 'Electronics', '2026-01-05', 1800),
	(6, 'Clothing', '2026-01-01', 700),
	(7, 'Clothing', '2026-01-02', 850),
	(8, 'Clothing', '2026-01-03', 950),
	(9, 'Clothing', '2026-01-04', 800),
	(10, 'Clothing', '2026-01-05', 1000);


/*CATEGORY 1 — MOVING AVERAGE:
QUESTION 1:
DEPARTMENT, SALE_DATE, SALES 
2 - DAY MOVING AVERAGE OF SALES PER DEPARTMENT*/

SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES
	AVG(SALES) OVER(PARTITION BY DEPARTMENT
	ORDER BY SALE_DATE
	ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
	) AS MOVING_AVG
FROM DEPARTMENT_SALES

/* QUESTION 2:
USING YOUR DEPARTMENT_SALES TABLE,
WRITE A QUERY TO SHOW:
DEPARTMENT, SALE_DATE, SALES
3- DAY MOVING AVERAGE OF SALES PER DEPARTMENT*/

SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	AVG(SALES) OVER(PARTITION BY DEPARTMENT
	ORDER BY SALE_DATE 
	ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MOVING_AVG
FROM DEPARTMENT_SALES;

/* CATEGORY 2 — COMPARING SALES VS DEPARTMENT AVERAGE
QUESTION 1:
SHOW: DEPARTMENT, SALE_DATE, SALES 
AVERAGE SALES OF THAT DEPARTMENT */
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	AVG(SALES) OVER(PARTITION BY DEPARTMENT) AS DEPT_AVG_SALES
FROM DEPARTMENT_SALES;

/* QUESTION 2:
SHOW: DEPARTMENT, SALE_DATE, SALES, DEPARTMENT AVERAGE SALES,
DIFFERENCE BETWEEN CURRENT SALES AND DEPARTMENT AVERAGE  */

SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	AVG(SALES) OVER(PARTITION BY DEPARTMENT) AS DEPT_AVG,
	SALES - AVG(SALES) OVER(PARTITION BY DEPARTMENT) AS FINAL_AVG
FROM DEPARTMENT_SALES;