--Write a query to display:
--employee name, salary, dense rank of salary (highest salary = rank 1)
SELECT NAME AS EMPLOYEE_NAME, SALARY,
	DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES;

--Find employees who have top 3 highest salaries
WITH CTE AS(
SELECT NAME AS EMPLOYEE_NAME, SALARY,
	DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES
)
SELECT EMPLOYEE_NAME, SALARY, RANK_
FROM CTE
WHERE RANK_ <= 3;

--Top 2 highest salaries in each department (using DENSE_RANK)
WITH CTE AS(
SELECT NAME AS EMPLOYEE_NAME, DEPT_ID, SALARY,
	DENSE_RANK() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES
)
SELECT EMPLOYEE_NAME, DEPT_ID, SALARY, RANK_
FROM CTE
WHERE RANK_ <= 2;

--Find: employee name, salary, dense rank of salary
WITH CTE AS(
SELECT NAME AS EMPLOYEE_NAME, SALARY,
	DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES
)
SELECT EMPLOYEE_NAME, SALARY, RANK_
FROM CTE
WHERE RANK_ = 2;

--Find: employee name, department id, salary
WITH CTE AS(
SELECT NAME AS EMPLOYEE_NAME, DEPT_ID, SALARY,
	DENSE_RANK() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES
)
SELECT EMPLOYEE_NAME, DEPT_ID, SALARY, RANK_
FROM CTE
WHERE RANK_ = 1;

--Find employees who have the second highest salary in each department
WITH CTE AS(
SELECT NAME AS EMPLOYEE_NAME, DEPT_ID, SALARY,
	DENSE_RANK() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RANK_
FROM EMPLOYEES
)
SELECT EMPLOYEE_NAME, DEPT_ID, SALARY, RANK_
FROM CTE
WHERE RANK_ = 2;




