--TABLE CREATION:
CREATE TABLE EMPLOYEES(
EMP_ID INT,
EMP_NAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT,
JOINING_DATE DATE
);

--INSERTING DATA:
INSERT INTO EMPLOYEES VALUES
(1, 'Mahesh', 'IT', 50000, '2022-01-10'),
(2, 'Rahul', 'IT', 55000, '2022-03-15'),
(3, 'Priya', 'IT', 60000, '2022-05-20'),
(4, 'Anjali', 'HR', 40000, '2022-02-01'),
(5, 'Kiran', 'HR', 45000, '2022-06-10'),
(6, 'Vijay', 'HR', 47000, '2022-08-05');

--PREVIOUS SALARY:
SELECT EMP_NAME, SALARY,
LAG(SALARY) OVER(ORDER BY SALARY) AS PREVIOUS_SALARY
FROM EMPLOYEES;

--PARTITION BY DEPARTMENT:
SELECT EMP_NAME, DEPARTMENT, SALARY,
LAG(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) AS PREVIOUS_SALARY
FROM EMPLOYEES;


--TABLE CREATION:
CREATE TABLE SALES(
SALE_DATE DATE,
SALES INT
);

--INSERTING DATA:
INSERT INTO SALES VALUES
	('2025-01-01', 100),
	('2025-01-02', 150),
	('2025-01-03', 120),
	('2025-01-04', 180),
	('2025-01-05', 200);

--PREVIOUS SALES:
SELECT SALE_DATE, SALES,
LAG(SALES) OVER(ORDER BY SALE_DATE) AS PREVIOUS_DAY_SALES
FROM SALES;

--COMPARING CURRENT SALES - PREVIOUS SALES:
SELECT
	SALE_DATE,
	SALES,
	SALES - LAG(SALES) OVER (ORDER BY SALE_DATE) AS DIFFERENCE
FROM SALES;

--MONTH - OVER - MONTH GROWTH:
SELECT
	SALE_DATE,
	SALES,
	LAG(SALES) OVER(ORDER BY SALE_DATE) AS PREVIOUS_SALES,

	SALES - LAG(SALES) OVER(ORDER BY SALE_DATE) AS DIFFERENCE
FROM SALES;

--PERCENTAGE GROWTH:
SELECT
	SALE_DATE,
	SALES,
	ROUND(
		(
			SALES - LAG(SALES) OVER (
				ORDER BY
					SALE_DATE
			)
		) * 100.0 / LAG(SALES) OVER (
			ORDER BY
				SALE_DATE
		),
		2
	) AS GROWTH_PERCENT
FROM
	SALES;
	

--TABLE CREATION:
CREATE TABLE DEPARTMENT_SALES(
	DEPARTMENT VARCHAR(20),
	SALE_DATE DATE,
	SALES INT
);

--INSERTING DATA:
INSERT INTO DEPARTMENT_SALES VALUES
	('IT', '2025-01-01', 100),
	('IT', '2025-01-02', 150),
	('IT', '2025-01-03', 120),
	('HR', '2025-01-01', 80),
	('HR', '2025-01-02', 90),
	('HR', '2025-01-03', 110);

--PARTITION WITH OFFSET:
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	LAG(SALES, 2) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE) AS PREVIOUS_SALES
FROM DEPARTMENT_SALES;

--OFFSET AND DEFAULT VALUE
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	LAG(SALES, 2, 0) OVER(ORDER BY SALE_DATE) AS PREVIOUS_SALES
FROM DEPARTMENT_SALES;

--CTE:
WITH CTE AS(
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	
	LAG(SALES, 2, 0) OVER(ORDER BY SALE_DATE) AS PREVIOUS_SALES
FROM DEPARTMENT_SALES
)
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,
	PREVIOUS_SALES
FROM CTE
WHERE SALES > PREVIOUS_SALES;