--TABLE CREATION:
CREATE TABLE DEPARTMENT_SALES (
	ID INT,
	DEPARTMENT VARCHAR(50),
	SALE_DATE DATE,
	SALES INT
);

--INSERTING DATA
INSERT INTO
	DEPARTMENT_SALES
VALUES
	(1, 'Electronics', '2026-01-01', 1000),
	(2, 'Electronics', '2026-01-02', 1200),
	(3, 'Electronics', '2026-01-03', 900),
	(4, 'Electronics', '2026-01-04', 1500),
	(5, 'Electronics', '2026-01-05', 1800),
	(6, 'Clothing', '2026-01-01', 700),
	(7, 'Clothing', '2026-01-02', 850),
	(8, 'Clothing', '2026-01-03', 950),
	(9, 'Clothing', '2026-01-04', 800),
	(10, 'Clothing', '2026-01-05', 1000);


--NEXT SALES:
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,

	LEAD(SALES) OVER(ORDER BY SALE_DATE) AS NEXT_SALES
FROM DEPARTMENT_SALES;

--SALES AFTER 2 DAYS = OFFSET:
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	LEAD(SALES, 2) OVER(ORDER BY SALE_DATE) AS NEXT_2DAYS_SALES
FROM DEPARTMENT_SALES;

--NEXT SALES WITH DEFAULT VALUE:
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	LEAD(SALES, 1, 0) OVER(ORDER BY SALE_DATE) AS NEXT_SALES
FROM DEPARTMENT_SALES;

--NEXT SALES INSIDE EACH DEPARTMENT ONLY(PARTITION):
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	LEAD(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE) AS NEXT_SALES
FROM DEPARTMENT_SALES;

--COMPARISON LOGIC:
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	LEAD(SALES) OVER(ORDER BY SALE_DATE) AS NEXT_SALES,
	
	CASE
	WHEN SALES < LEAD(SALES) OVER(ORDER BY SALE_DATE)

	THEN 
	'INCREASE'

	ELSE
	'DECREASE'
	END AS STATUS
FROM DEPARTMENT_SALES;

--PROBLEM SOLVING(DIFFERENCE):
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	
	LEAD(SALES) OVER(ORDER BY SALE_DATE) AS NEXT_SALES,

	SALES - LEAD(SALES) OVER(ORDER BY SALE_DATE) AS DIFFERENCE

FROM DEPARTMENT_SALES;

--ADVANCED(PERCENTAGE GROWTH):
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	LEAD(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE) AS NEXT_SALES,

	ROUND
	(
		(SALES - LEAD(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE)
	) * 100.0
		/
		LEAD(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE), 2
	) AS GROWTH_PERCENTAGE
FROM DEPARTMENT_SALES;

--CTE + WINDOWS FUNCTION:
WITH CTE AS(
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,
	LEAD(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE) AS NEXT_SALES
FROM DEPARTMENT_SALES
)
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,
	NEXT_SALES,
	ROUND
	(
		(SALES - NEXT_SALES
	) * 100.0
	
		/
		
		NEXT_SALES, 2
	) AS GROWTH_PERCENTAGE
FROM CTE;




