--Rank all employees by salary (highest first)
SELECT NAME, SALARY,
	ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS RN
FROM EMPLOYEES;

--Top 2 salaries in each department
WITH RANKED_EMP AS(
SELECT *, 
ROW_NUMBER() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RN
FROM EMPLOYEES
)
SELECT * FROM RANKED_EMP
WHERE RN <= 2;

--Find 2nd highest salary in each department
WITH RANKED_SAL AS(
SELECT *, 
	ROW_NUMBER() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RN
	FROM EMPLOYEES
)
SELECT * FROM RANKED_SAL
WHERE RN = 2;

--Find LOWEST salary employee in each department
WITH MIN_SAL AS(
SELECT *, 
	ROW_NUMBER() OVER(PARTITION BY DEPT_ID ORDER BY SALARY ASC) AS RN
FROM EMPLOYEES
)
SELECT NAME, DEPT_ID, SALARY FROM MIN_SAL
WHERE RN = 1;

--Remove duplicate salaries in same department
--Keep only the row with highest EMP_ID
WITH HIGHEST_EMP AS(
SELECT *,
	ROW_NUMBER() OVER(PARTITION BY DEPT_ID, SALARY ORDER BY EMP_ID DESC) AS RN
FROM EMPLOYEES
)
SELECT NAME, DEPT_ID, SALARY
FROM HIGHEST_EMP
WHERE RN = 1;

--Find employees whose salary rank is between 2 and 4 (overall)
WITH RANKED_SAL AS(
SELECT *,
	ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS RN
FROM EMPLOYEES
)
SELECT NAME, DEPT_ID, SALARY FROM RANKED_SAL
WHERE RN BETWEEN 2 AND 4; 

--Find 2nd LOWEST salary in each department
WITH RANKED_MIN_SAL AS(
SELECT *,
	ROW_NUMBER() OVER(PARTITION BY DEPT_ID ORDER BY SALARY ASC) AS RN
FROM EMPLOYEES
)
SELECT NAME, DEPT_ID, SALARY FROM RANKED_MIN_SAL
WHERE RN = 2;