--TABLE CREATION:
CREATE TABLE DEPARTMENT_SALES (
	ID INT,
	DEPARTMENT VARCHAR(50),
	SALE_DATE DATE,
	SALES INT
);

--INSERTING DATA
INSERT INTO
	DEPARTMENT_SALES
VALUES
	(1, 'Electronics', '2026-01-01', 1000),
	(2, 'Electronics', '2026-01-02', 1200),
	(3, 'Electronics', '2026-01-03', 900),
	(4, 'Electronics', '2026-01-04', 1500),
	(5, 'Electronics', '2026-01-05', 1800),
	(6, 'Clothing', '2026-01-01', 700),
	(7, 'Clothing', '2026-01-02', 850),
	(8, 'Clothing', '2026-01-03', 950),
	(9, 'Clothing', '2026-01-04', 800),
	(10, 'Clothing', '2026-01-05', 1000);


/*RUNNING TOTALS QUESTION 1:

USING DEPARTMENT_SALES TABLE,
WRITE A QUERY TO DISPLAY:SALE_DATE, SALES, 
RUNNING TOTAL OF SALES BASED ON SALE_DATE */

WITH CTE AS(
SELECT 
	SALE_DATE,
	SALES,

	SUM(SALES) OVER(ORDER BY SALE_DATE) AS RUNNING_TOTALS

FROM DEPARTMENT_SALES
)
SELECT 
	SALE_DATE,
	SALES,
	RUNNING_TOTALS
FROM CTE;

/*RUNNING TOTALS QUESTION 2:
WRITE A QUERY TO DISPLAY:DEPARTMENT, SALE_DATE, SALES,
RUNNING TOTAL OF SALES SEPARATELY FOR EACH DEPARTMENT BASED ON SALE_DATE 
DO NOT COLLAPSE ROWS.*/

WITH CTE AS(
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,

	SUM(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE) AS RUNNING_TOTALS

FROM DEPARTMENT_SALES
)
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,
	RUNNING_TOTALS
FROM CTE;

/*CUMULATIVE SALES — QUESTION 1:

WRITE A QUERY TO DISPLAY:
SALE_DATE
SALES
CUMULATIVE SALES ACROSS THE ENTIRE TABLE ORDERED BY SALE_DATE*/

SELECT
    SALE_DATE,
    SALES,

    SUM(SALES) OVER(ORDER BY SALE_DATE) AS CUMULATIVE_SALES

FROM DEPARTMENT_SALES;

/*CUMULATIVE SALES — QUESTION 2
WRITE A QUERY TO DISPLAY: DEPARTMENT, SALE_DATE, SALES,
CUMULATIVE SALES SEPARATELY FOR EACH DEPARTMENT ORDERED BY 
SALE_DATE*/

SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,

	SUM(SALES) OVER(PARTITION BY DEPARTMENT ORDER BY SALE_DATE) AS CUMULATIVE_SALES
FROM DEPARTMENT_SALES;	

/*TOTAL PER DEPARTMENT — QUESTION 1

WRITE A QUERY TO DISPLAY: DEPARTMENT, SALE_DATE, SALES
TOTAL SALES FOR EACH DEPARTMENT ON EVERY ROW*/
SELECT 
	DEPARTMENT,
	SALE_DATE,
	SALES,

	SUM(SALES) OVER(PARTITION BY DEPARTMENT) AS DEPARTMENT_TOTAL
FROM DEPARTMENT_SALES;	

/*  WRITE A QUERY TO DISPLAY: ID, DEPARTMENT, SALE_DATE, SALES
TOTAL SALES FOR EACH DEPARTMENT
ORDER FINAL OUTPUT BY:
DEPARTMENT, SALE_DATE    */
WITH CTE AS(
SELECT
	ID,
	DEPARTMENT,
	SALE_DATE,
	SALES,

	SUM(SALES) OVER(PARTITION BY DEPARTMENT) AS DEPARTMENT_TOTAL
FROM DEPARTMENT_SALES	
)
SELECT
	ID,
	DEPARTMENT,
	SALE_DATE,
	SALES,
	DEPARTMENT_TOTAL
FROM CTE
ORDER BY DEPARTMENT, SALE_DATE;

/*CONTRIBUTION ANALYSIS — QUESTION 1

WRITE A QUERY TO DISPLAY: DEPARTMENT, SALE_DATE, SALES
PERCENTAGE CONTRIBUTION OF EACH ROW TO TOTAL SALES ACROSS THE ENTIRE 
TABLE*/
WITH CTE AS(
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	SUM(SALES) OVER() AS TOTAL_SALES
FROM DEPARTMENT_SALES
)
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	ROUND(
		SALES * 100.0
			/
			TOTAL_SALES, 2
	) AS PERCENTAGE_CONTRIBUTION
FROM CTE;

/*CONTRIBUTION ANALYSIS — QUESTION 2
WRITE A QUERY TO DISPLAY: DEPARTMENT, SALE_DATE, SALES
PERCENTAGE CONTRIBUTION OF EACH ROW WITHIN ITS OWN DEPARTMENT
EXAMPLE IDEA:
ELECTRONICS ROWS CONTRIBUTE ONLY AGAINST ELECTRONICS TOTAL CLOTHING 
ROWS CONTRIBUTE ONLY AGAINST CLOTHING TOTAL*/
WITH CTE AS(
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,
	SUM(SALES) OVER(PARTITION BY DEPARTMENT) AS TOTAL_SALES
FROM DEPARTMENT_SALES
)
SELECT
	DEPARTMENT,
	SALE_DATE,
	SALES,

	ROUND(
		SALES * 100.0
			/
			TOTAL_SALES, 2
	) AS DEPARTMENT_CONTRIBUTION_PERCENT
FROM CTE;