--INSERT ONE RECORD
INSERT INTO STUDENTS(STUDENT_ID, NAME, AGE, COURSE)
VALUES(1, 'MAHESH', 20, 'ECE');

--INSERT ANOTHER RECORD
INSERT INTO STUDENTS(STUDENT_ID, NAME, AGE, COURSE)
VALUES(2, 'PRIYA', 21, 'CSE');

--INSERT MULTIPLE RECORDS IN ONE QUERY
INSERT INTO STUDENTS(STUDENT_ID, NAME, AGE, COURSE)
VALUES(3, 'KRISHNA', 21, 'ECE'),
	  (4, 'GOWTHAM', 20, 'CSE'),
	  (5, 'SRINIDHI', 22, 'MECH');

--INSERT WITHOUT COLUMN NAMES
INSERT INTO Students
VALUES(6, 'GEETHA', 21, 'EEE');

--INSERT PARTIAL COLUMNS
INSERT INTO STUDENTS(STUDENT_ID, NAME)
VALUES(7, 'RIO');

--TO VIEW TABLE
SELECT * FROM STUDENTS;

