--1️ Basic MIN
--Find the lowest salary in the company:
SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES;

--2️ Basic MAX
--Find the highest salary in the company:
SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEES;

--3️ MIN/MAX per Department (GROUP BY)
--Lowest salary per department:
SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;
--Highest salary per department:
SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

--4️ MIN/MAX with multiple columns
--Lowest and highest salary per department and gender:
SELECT DEPARTMENT, GENDER, 
MIN(SALARY) AS MIN_SALARY,
MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES
GROUP BY DEPARTMENT, GENDER;

--5️ MIN/MAX with WHERE
--Lowest salary in Sales department:
SELECT MIN(SALARY) AS LOWEST_SALES_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT LIKE 'Sales';
--Highest salary in IT department:
SELECT MAX(SALARY) AS HIGHEST_SALES_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT LIKE 'Sales';

--6 MIN/MAX with HAVING
--Departments where the highest salary exceeds 65000:
SELECT DEPARTMENT, MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING MAX(SALARY) > 65000;

--7 MIN/MAX with DISTINCT
--Find the lowest unique salary:
SELECT MIN(DISTINCT SALARY) AS MIN_UNIQUE_SALARY
FROM EMPLOYEES;
--Find the lowest unique salary:
SELECT MAX(DISTINCT SALARY) AS MAX_UNIQUE_SALARY
FROM EMPLOYEES;