--🟠 LEVEL 3 (CTE + JOIN)
--Find employees earning more than their department average
WITH AVG_SAL AS (
SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT E.* FROM EMPLOYEES E
INNER JOIN AVG_SAL A
ON E.DEPT_ID = A.DEPT_ID
WHERE E.SALARY > A.AVG_SALARY;

--Find employees earning less than their department average
WITH AVG_SAL AS (
SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT E.* FROM EMPLOYEES E
INNER JOIN AVG_SAL A
ON E.DEPT_ID = A.DEPT_ID
WHERE E.SALARY < A.AVG_SALARY;

--Show employee name along with their department average salary
WITH AVG_SAL AS (
SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT E.NAME, E.DEPT_ID, A.AVG_SALARY FROM EMPLOYEES E
INNER JOIN AVG_SAL A
ON E.DEPT_ID = A.DEPT_ID;