--🟡 LEVEL 2 (GROUP BY + CTE)
--Find department-wise average salary
WITH AVG_SAL AS (
SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT * FROM AVG_SAL;

--Find department-wise maximum salary
WITH MAX_SAL AS (
SELECT DEPT_ID, MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT * FROM MAX_SAL;

--Find department-wise total salary
WITH SUM_DEPT_SAL AS (
SELECT DEPT_ID, SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID
)
SELECT * FROM SUM_DEPT_SAL;