--🔵 LEVEL 4 (Multiple CTEs)
--Find employees earning more than overall average AND department average
WITH OVERALL_AVG AS (
SELECT AVG(SALARY) AS AVG_SAL FROM EMPLOYEES),
DEPT_AVG AS (
SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID)
SELECT E.* FROM EMPLOYEES E
JOIN DEPT_AVG D
ON E.DEPT_ID = D.DEPT_ID
JOIN OVERALL_AVG O
ON 1 = 1
WHERE E.SALARY > D.AVG_SALARY AND E.SALARY > O.AVG_SAL;

--Find where departments average salary is greater than overall average
WITH DEPT_AVG AS (
SELECT DEPT_ID, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES
GROUP BY DEPT_ID),
OVERALL_AVG AS (
SELECT AVG(SALARY) AS AVG_SAL FROM EMPLOYEES
)
SELECT D.DEPT_ID, D.AVG_SALARY, O.AVG_SAL FROM DEPT_AVG D
JOIN OVERALL_AVG O
ON 1 = 1
WHERE D.AVG_SALARY > O.AVG_SAL;

--Get employees from departments where total salary > 100000
WITH TOTAL_SAL AS (
SELECT DEPT_ID, SUM(SALARY) AS DEPT_SAL FROM EMPLOYEES
GROUP BY DEPT_ID)
SELECT E.NAME, E.DEPT_ID, T.DEPT_SAL FROM EMPLOYEES E
JOIN TOTAL_SAL T
ON E.DEPT_ID = T.DEPT_ID
WHERE T.DEPT_SAL > 100000;