CREATE TABLE DEPARTMENTS (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50)
);

CREATE TABLE EMPLOYEES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPT_ID INT,
    SALARY INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);


INSERT INTO DEPARTMENTS VALUES
(1, 'IT'),
(2, 'HR'),
(3, 'Finance');

INSERT INTO EMPLOYEES VALUES
(1, 'Ram', 1, 50000),
(2, 'Sam', 2, 40000),
(3, 'John', 1, 60000),
(4, 'Sara', 3, 45000),
(5, 'Ravi', 1, 55000),
(6, 'Anu', 2, 42000),
(7, 'Kiran', 3, 70000);



--🧠 LEVEL 1 — Basics (JOIN + FILTER)
--Show all employees with their department names
SELECT E.ID, E.NAME, E.DEPT_ID, E.SALARY, D.DEPT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID;

--Get employees who work in 'IT' department
--Show: ID, NAME, DEPT_NAME, SALARY
SELECT E.ID, E.NAME, D.DEPT_NAME, E.SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.DEPT_NAME = 'IT';

--List employees with salary greater than 50,000
--Show: ID, NAME, SALARY
SELECT ID, NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 50000;

--Show employee names and salaries sorted by salary descending
SELECT NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;

--Get employees whose name starts with 'R'
SELECT ID, NAME FROM EMPLOYEES
WHERE NAME LIKE 'R%';

--🧠 LEVEL 2 — JOIN + CONDITIONS
--Display employee name and department name where salary < 45,000
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
WHERE SALARY < 45000;

--Get employees who belong to 'HR' or 'Finance'
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.DEPT_NAME = 'HR' OR D.DEPT_NAME = 'Finance';

--Show employees not working in 'IT'
SELECT E.NAME, D.DEPT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.DEPT_NAME != 'IT';

--List employees with salary between 40,000 and 60,000
SELECT NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 60000;

--Show employees ordered by department name and then salary
--Show: NAME, DEPT_NAME, SALARY
SELECT E.NAME, D.DEPT_NAME, E.SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
ORDER BY D.DEPT_NAME ASC, E.SALARY DESC;

--Count number of employees in each department
--Show: DEPT_NAME, COUNT
SELECT D.DEPT_NAME, COUNT(E.ID) FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_NAME;

--Find maximum salary in each department
--Show: DEPT_NAME, MAX_SALARY
SELECT D.DEPT_NAME, MAX(E.SALARY) FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

--Get minimum salary across all employees
SELECT MIN(SALARY) AS MIN_SALARY FROM EMPLOYEES;

--Find average salary of each department
SELECT D.DEPT_NAME, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

--Get total salary paid in each department
SELECT D.DEPT_NAME, SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

--Find departments having more than 2 employees
--Show: DEPT_NAME, EMP_COUNT
SELECT D.DEPT_NAME, COUNT(E.ID) AS EMP_COUNT FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING COUNT(*) > 2;

--Show departments where average salary > 50,000
SELECT D.DEPT_NAME, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING AVG(E.SALARY) > 50000;

--Get departments with total salary > 1,00,000
SELECT D.DEPT_NAME, SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING SUM(E.SALARY) > 100000;

--Find departments where maximum salary > 60,000
SELECT D.DEPT_NAME, MAX(E.SALARY) AS MAX_SALARY FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING MAX(E.SALARY) > 60000;

--Count employees per department
--Show only departments with count >= 2
--Show: DEPT_NAME, EMP_COUNT
SELECT D.DEPT_NAME, COUNT(E.ID) AS EMP_COUNT FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING COUNT(*) >= 2;

--Find employees earning more than average salary
--Show: NAME, SALARY
SELECT NAME, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--Get employees with highest salary
--Show: NAME, SALARY
SELECT NAME, SALARY FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES);

--Find employees whose salary equals second highest salary
--Show: NAME, SALARY
SELECT NAME, SALARY FROM EMPLOYEES
WHERE SALARY = (SELECT SALARY FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1 OFFSET 1);

--Get employees earning less than the highest salary
--Show: NAME, SALARY
SELECT NAME, SALARY FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES);